"""agrego external_api_id a teams

Revision ID: 7918015f2b32
Revises: 9370d3abee32
Create Date: 2026-08-16 16:03:39.298007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7918015f2b32'
down_revision: Union[str, Sequence[str], None] = '9370d3abee32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('external_api_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_teams_external_api_id'), 'teams', ['external_api_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_external_api_id'), table_name='teams')
    op.drop_column('teams', 'external_api_id')
    # ### end Alembic commands ###
