"""agrego palmares entries

Revision ID: 89aca2c8de66
Revises: edfd22f8016d
Create Date: 2026-08-16 17:46:46.512474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89aca2c8de66'
down_revision: Union[str, Sequence[str], None] = 'edfd22f8016d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('palmares_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('competition', sa.String(), nullable=False),
    sa.Column('champion_count', sa.Integer(), nullable=False),
    sa.Column('runner_up_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'competition', name='uq_palmares_team_competition')
    )
    op.create_index(op.f('ix_palmares_entries_competition'), 'palmares_entries', ['competition'], unique=False)
    op.create_index(op.f('ix_palmares_entries_team_id'), 'palmares_entries', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_palmares_entries_team_id'), table_name='palmares_entries')
    op.drop_index(op.f('ix_palmares_entries_competition'), table_name='palmares_entries')
    op.drop_table('palmares_entries')
    # ### end Alembic commands ###
