"""estado inicial

Revision ID: 8de0ba3a06fd
Revises: 
Create Date: 2026-08-14 20:36:04.713445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8de0ba3a06fd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('founded_year', sa.Integer(), nullable=False),
    sa.Column('primary_color', sa.String(length=7), nullable=False),
    sa.Column('secondary_color', sa.String(length=7), nullable=False),
    sa.Column('accent_color', sa.String(length=7), nullable=False),
    sa.Column('shield_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_teams_name', 'teams', ['name'], unique=False)
    op.create_index(op.f('ix_teams_slug'), 'teams', ['slug'], unique=True)
    op.create_table('idols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('period_start', sa.Integer(), nullable=True),
    sa.Column('period_end', sa.Integer(), nullable=True),
    sa.Column('matches', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('titles_count', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idols_team_id'), 'idols', ['team_id'], unique=False)
    op.create_index('ix_idols_team_name', 'idols', ['team_id', 'name'], unique=False)
    op.create_table('kits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('decade', sa.String(length=10), nullable=False),
    sa.Column('season', sa.String(length=20), nullable=False),
    sa.Column('brand', sa.String(length=60), nullable=True),
    sa.Column('sponsor', sa.String(length=80), nullable=True),
    sa.Column('competition_highlight', sa.String(length=120), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kits_decade'), 'kits', ['decade'], unique=False)
    op.create_index('ix_kits_team_decade', 'kits', ['team_id', 'decade'], unique=False)
    op.create_index(op.f('ix_kits_team_id'), 'kits', ['team_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('venue', sa.String(length=120), nullable=True),
    sa.Column('competition', sa.String(length=80), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('round_label', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'PLAYED', 'POSTPONED', 'CANCELLED', name='matchstatus'), nullable=False),
    sa.Column('home_goals', sa.Integer(), nullable=True),
    sa.Column('away_goals', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_away_team_id'), 'matches', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_matches_competition'), 'matches', ['competition'], unique=False)
    op.create_index('ix_matches_home_away', 'matches', ['home_team_id', 'away_team_id'], unique=False)
    op.create_index(op.f('ix_matches_home_team_id'), 'matches', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_matches_scheduled_at'), 'matches', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_matches_season'), 'matches', ['season'], unique=False)
    op.create_index('ix_matches_season_competition', 'matches', ['season', 'competition'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('shirt_number', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('nationality', sa.String(length=60), nullable=False),
    sa.Column('position_group', sa.Enum('ARQUERO', 'DEFENSOR', 'MEDIOCAMPISTA', 'DELANTERO', name='positiongroup'), nullable=False),
    sa.Column('position', sa.String(length=40), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('contract_until', sa.Date(), nullable=True),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_position_group'), 'players', ['position_group'], unique=False)
    op.create_index('ix_players_team_group', 'players', ['team_id', 'position_group'], unique=False)
    op.create_index(op.f('ix_players_team_id'), 'players', ['team_id'], unique=False)
    op.create_index('ix_players_team_number', 'players', ['team_id', 'shirt_number'], unique=False)
    op.create_table('rivalries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('rival_team_id', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('draws', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('goals_for', sa.Integer(), nullable=False),
    sa.Column('goals_against', sa.Integer(), nullable=False),
    sa.Column('last_match_at', sa.DateTime(), nullable=True),
    sa.Column('is_primary_classic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rival_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'rival_team_id', name='uq_rivalry_team_rival')
    )
    op.create_index(op.f('ix_rivalries_is_primary_classic'), 'rivalries', ['is_primary_classic'], unique=False)
    op.create_index(op.f('ix_rivalries_rival_team_id'), 'rivalries', ['rival_team_id'], unique=False)
    op.create_index('ix_rivalries_team_classic', 'rivalries', ['team_id', 'is_primary_classic'], unique=False)
    op.create_index(op.f('ix_rivalries_team_id'), 'rivalries', ['team_id'], unique=False)
    op.create_table('stadiums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('inaugurated_year', sa.Integer(), nullable=True),
    sa.Column('attendance_record', sa.Integer(), nullable=True),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stadiums_team_id'), 'stadiums', ['team_id'], unique=True)
    op.create_table('standing_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('competition', sa.String(), nullable=False),
    sa.Column('zone', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('played', sa.Integer(), nullable=False),
    sa.Column('won', sa.Integer(), nullable=False),
    sa.Column('drawn', sa.Integer(), nullable=False),
    sa.Column('lost', sa.Integer(), nullable=False),
    sa.Column('goals_for', sa.Integer(), nullable=False),
    sa.Column('goals_against', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'season', 'competition', name='uq_standing_team_season_competition')
    )
    op.create_index(op.f('ix_standing_entries_competition'), 'standing_entries', ['competition'], unique=False)
    op.create_index(op.f('ix_standing_entries_position'), 'standing_entries', ['position'], unique=False)
    op.create_index(op.f('ix_standing_entries_season'), 'standing_entries', ['season'], unique=False)
    op.create_index(op.f('ix_standing_entries_team_id'), 'standing_entries', ['team_id'], unique=False)
    op.create_index('ix_standing_season_competition_position', 'standing_entries', ['season', 'competition', 'position'], unique=False)
    op.create_table('trophies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('trophy_type', sa.Enum('LIGA', 'COPA_NACIONAL', 'COPA_INTERNACIONAL', 'OTRO', name='trophytype'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('competition', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trophies_team_id'), 'trophies', ['team_id'], unique=False)
    op.create_index('ix_trophies_team_type_year', 'trophies', ['team_id', 'trophy_type', 'year'], unique=False)
    op.create_index(op.f('ix_trophies_trophy_type'), 'trophies', ['trophy_type'], unique=False)
    op.create_index(op.f('ix_trophies_year'), 'trophies', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trophies_year'), table_name='trophies')
    op.drop_index(op.f('ix_trophies_trophy_type'), table_name='trophies')
    op.drop_index('ix_trophies_team_type_year', table_name='trophies')
    op.drop_index(op.f('ix_trophies_team_id'), table_name='trophies')
    op.drop_table('trophies')
    op.drop_index('ix_standing_season_competition_position', table_name='standing_entries')
    op.drop_index(op.f('ix_standing_entries_team_id'), table_name='standing_entries')
    op.drop_index(op.f('ix_standing_entries_season'), table_name='standing_entries')
    op.drop_index(op.f('ix_standing_entries_position'), table_name='standing_entries')
    op.drop_index(op.f('ix_standing_entries_competition'), table_name='standing_entries')
    op.drop_table('standing_entries')
    op.drop_index(op.f('ix_stadiums_team_id'), table_name='stadiums')
    op.drop_table('stadiums')
    op.drop_index(op.f('ix_rivalries_team_id'), table_name='rivalries')
    op.drop_index('ix_rivalries_team_classic', table_name='rivalries')
    op.drop_index(op.f('ix_rivalries_rival_team_id'), table_name='rivalries')
    op.drop_index(op.f('ix_rivalries_is_primary_classic'), table_name='rivalries')
    op.drop_table('rivalries')
    op.drop_index('ix_players_team_number', table_name='players')
    op.drop_index(op.f('ix_players_team_id'), table_name='players')
    op.drop_index('ix_players_team_group', table_name='players')
    op.drop_index(op.f('ix_players_position_group'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index('ix_matches_season_competition', table_name='matches')
    op.drop_index(op.f('ix_matches_season'), table_name='matches')
    op.drop_index(op.f('ix_matches_scheduled_at'), table_name='matches')
    op.drop_index(op.f('ix_matches_home_team_id'), table_name='matches')
    op.drop_index('ix_matches_home_away', table_name='matches')
    op.drop_index(op.f('ix_matches_competition'), table_name='matches')
    op.drop_index(op.f('ix_matches_away_team_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_kits_team_id'), table_name='kits')
    op.drop_index('ix_kits_team_decade', table_name='kits')
    op.drop_index(op.f('ix_kits_decade'), table_name='kits')
    op.drop_table('kits')
    op.drop_index('ix_idols_team_name', table_name='idols')
    op.drop_index(op.f('ix_idols_team_id'), table_name='idols')
    op.drop_table('idols')
    op.drop_index(op.f('ix_teams_slug'), table_name='teams')
    op.drop_index('ix_teams_name', table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
