"""agrego assists a idols

Revision ID: 9370d3abee32
Revises: c30716a1ac3a
Create Date: 2026-08-14 21:00:32.375584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9370d3abee32'
down_revision: Union[str, Sequence[str], None] = 'c30716a1ac3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idols', sa.Column('assists', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('idols', 'assists')
    # ### end Alembic commands ###
