"""agrego kit_type a kits

Revision ID: c30716a1ac3a
Revises: 8de0ba3a06fd
Create Date: 2026-08-14 20:50:03.137271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c30716a1ac3a'
down_revision: Union[str, Sequence[str], None] = '8de0ba3a06fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'kits',
        sa.Column('kit_type', sa.String(length=30), nullable=False, server_default='Local'),
    )
    # Sacamos el default de la columna en DB; el valor por defecto="Local"
    # ya queda manejado en el modelo Python (Kit.kit_type), no hace falta
    # que SQLite lo siga aplicando a futuras inserciones.
    with op.batch_alter_table('kits') as batch_op:
        batch_op.alter_column('kit_type', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kits', 'kit_type')
    # ### end Alembic commands ###
