"""agrego average a standing_entries

Revision ID: edfd22f8016d
Revises: d57c2c5eac56
Create Date: 2026-08-16 17:04:03.281324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edfd22f8016d'
down_revision: Union[str, Sequence[str], None] = 'd57c2c5eac56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standing_entries', sa.Column('average', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('standing_entries', 'average')
    # ### end Alembic commands ###
